apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: game-hub
  name: deployment-game-hub
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: game-hub
  template:
    metadata:
      labels:
        app.kubernetes.io/name: game-hub
    spec:
      containers:
        - name: game-hub
          image: 928413605425.dkr.ecr.us-east-1.amazonaws.com/development/game-hub:version1
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
